version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code/retc
    working_dir: /code/retc
    tty: true
  
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: /retc ${SOCKET_URL} ${HUB_SID} ${MESSAGE}
    
