FROM elixir:1.15.8-otp-26-alpine AS build

WORKDIR /code

RUN mix do local.hex --force, local.rebar --force
COPY . .
RUN mix deps.get  \
    && mix escript.build

FROM erlang:26-alpine
WORKDIR /app
COPY --from=build /code/retc /app/retc