version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code/retc
    working_dir: /code/retc
    tty: true
  
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: /app/retc 'wss://host.docker.internal:4000/socket/websocket?vsn=2.0.0' 'KBk9k4q' '300'
    
